### ISSUE TITLE
Is server-side scoped app required on PROD

### ISSUE THREAD

**Issue by mikebski** [nuvolo/sincronia#110]
It's not clear to me if we have to install the scoped app in PRD (sincronia-server-scoped-app)

Can we just keep in sync with DEV and publish the scoped app via our internal company app repository?

**Comment by collinparker-nuvolo** [comment]
If I understand correctly, you will not be using sincronia to push directly into PRD. If that is the case, then no you do not need the scoped app in PROD. You only need the scoped app in environments which sincronia will be pushing code to directly.
