### ISSUE TITLE
Scheduled/Polled routine pull of data from ServiceNow to pull in new files and updated XMLs

### ISSUE THREAD

**Issue by nabil-nuvolo** [nuvolo/sincronia#84]
- Consider optional arg for 2-way sync (pull new/update files from ServiceNow) when starting `dev` mode
-

**Comment by collinparker-nuvolo** [comment]
- separate manifest for xml files?
- just start with pulling once?
- routine pull?

**Comment by collinparker-nuvolo** [comment]
#58 dup
